[package]
name = "schmoo_torrent"
version = "0.1.0"
authors = ["kim"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
maplit = "1.0.2"
sha-1 = "0.8.2"